import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { AuthProvider } from '@/context/auth-context';
import { BranchProvider } from '@/context/branch-context';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Hauze Tenant Platform',
    description: 'Generated by Hauze',
};


import './globals.css';

import { RefreshProvider } from '@/context/refresh-context';
import QueryProvider from '@/context/query-provider';

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="tr">
            <body className={inter.className}>
                <AuthProvider>
                    <QueryProvider>
                        <RefreshProvider>
                            <BranchProvider>
                                {children}
                            </BranchProvider>
                        </RefreshProvider>
                    </QueryProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
